[package]
name = "xplor"
version = "0.1.0"
authors = ["Victor Yap <swe@vicyap.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.5.0-rc.1"
